FROM golang:1.10.2-alpine3.7

RUN apk update && apk add git
RUN go get -u github.com/Masterminds/glide

RUN glide install && \ 
CGO_ENABLED=0 go build \
-ldflags "-X $REPO/version=$(git describe --abbrev=0 --tags --always)"