NAME               := fivecolors
ROOT_REPO          := github.com/rjansen/$(NAME)
VERSION            := $(notdir $(shell git describe --tags --always))
BUILD              := $(VERSION).$(shell git rev-parse --short HEAD)
MAKEFILE           := $(lastword $(MAKEFILE_LIST))
BASE_DIR           := $(shell cd $(dir $(MAKEFILE)); pwd)
TMP_DIR            := $(BASE_DIR)/tmp
DOCKER_NAME        := e-pedion/$(NAME)
DOCKER_FILE        := ./etc/docker/Dockerfile

include .make/*.vars
