// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type Audio struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description *string  `json:"description"`
	Value       *float64 `json:"value"`
	Singer      string   `json:"singer"`
	Compositor  string   `json:"compositor"`
	Duration    *float64 `json:"duration"`
}

func (Audio) IsProduct()      {}
func (Audio) IsSearchResult() {}

type Book struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description *string  `json:"description"`
	Value       *float64 `json:"value"`
	Isbn        string   `json:"isbn"`
	Author      string   `json:"author"`
	Flavor      *string  `json:"flavor"`
}

func (Book) IsProduct()      {}
func (Book) IsSearchResult() {}

type Product interface {
	IsProduct()
}

type ProductFilter struct {
	ID    *string  `json:"id"`
	Name  *string  `json:"name"`
	Value *float64 `json:"value"`
}

type SearchResult interface {
	IsSearchResult()
}

type Video struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description *string  `json:"description"`
	Value       *float64 `json:"value"`
	Director    string   `json:"director"`
	Writer      string   `json:"writer"`
	Actors      []string `json:"actors"`
	Duration    *float64 `json:"duration"`
}

func (Video) IsProduct()      {}
func (Video) IsSearchResult() {}
