FROM alpine:3.8

RUN rm -rf /var/cache/apk/* && \
    apk update && \
    apk add jq curl tzdata ca-certificates && \
    update-ca-certificates && \
    cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
    echo "America/Sao_Paulo" > /etc/timezone && \
    apk del tzdata && \
    rm -rf /var/cache/apk/*

COPY asset /app/asset
WORKDIR /app
CMD ["./asset"]